/*
 * HnSRTreeOffset.cc
 *
 * DO NOT EDIT THIS FILE!
 *
 * This file is automatically generated by obj2ptr.
 * 1997/06/02 21:19:33
 */

#include "HnSRTreeOffset.hh"
#include "HnSRTreeOffsetObj.hh"

/*
 * HnSRTreeOffset
 */

const HnSRTreeOffset HnSRTreeOffset::null;

HnSRTreeOffset
new_HnSRTreeOffset(off_t value)
{
	HnSRTreeOffsetObj *_obj;
	HnSRTreeOffset _ptr;

	_obj = new HnSRTreeOffsetObj(value);

	if(_obj->hasFailed())
		return HnSRTreeOffset::null;

	_ptr.assign(_obj);
	return _ptr;
}

off_t
HnSRTreeOffset::getValue(void) const
{
	return getObject()->getValue();
}

HnBool
HnSRTreeOffset::equals(const HnSRTreeOffset &ptr) const {
	if(isInvalid()) {
		if(ptr.isInvalid())
			return HnTRUE;
		else
			return HnFALSE;
    	}
    	else {
		if(ptr.isInvalid())
			return HnFALSE;
		else
			return getObject()->equals(ptr);
	}
}

HnString
HnSRTreeOffset::toString(void) const {
	if(isInvalid())
		return "HnSRTreeOffset::null";
    	else
		return getObject()->toString();
}

HnSRTreeOffset::operator off_t(void) const
{
	return getObject()->operator off_t();
}

/*
 * HnSRTreeOffsetArrayObj
 */

#include <stdlib.h>
#include "HnString.hh"
class HnSRTreeOffsetArrayObj: public HnObject {
private:
	HnSRTreeOffset **array;
	int len;
	int size;

	static const int initialSize;

	void initialize(void) {
		array = NULL;
		len = 0;
		size = 0;
	}
	void dispose(void) {
		if(array != NULL) {
			int i;
			for(i=0; i<len; i++)
				delete array[i];
			free(array);
		}
		array = NULL;
		len = 0;
		size = 0;
	}
	void ensureSize(int requiredSize);

public:
	/* constructor and destructor */
	HnSRTreeOffsetArrayObj(void);
	HnSRTreeOffsetArrayObj(const HnSRTreeOffsetArray &ptr);
	~HnSRTreeOffsetArrayObj(void);

	/* clear, append, insert, and remove */
	void clear(void);
	void append(const HnSRTreeOffset &ptr);
	void append(const HnSRTreeOffsetArray &ptr);
	void insert(const HnSRTreeOffset &ptr, int index);
	HnSRTreeOffset remove(int index);
	void set(const HnSRTreeOffset &ptr, int index);
	void swap(int i, int j);

	/* length and get */
	int length(void) const { return len; }
	HnSRTreeOffset &get(int i) const;

	/* utilities */
	HnBool equals(const HnSRTreeOffsetArray &ptr) const;
	int indexOf(const HnSRTreeOffset &ptr, int fromIndex) const;
	HnString toString(void) const;
};

const int HnSRTreeOffsetArrayObj::initialSize = 4;

static void *
xrealloc(void *ptr, size_t size)
{
        if(ptr == NULL) {
                if((ptr = malloc(size)) == NULL)
                        HnSysError("malloc");
        }
        else {
                if((ptr = realloc(ptr, size)) == NULL)
                        HnSysError("realloc");
        }

        return ptr;
}

void
HnSRTreeOffsetArrayObj::ensureSize(int requiredSize)
{
	int oldSize, newSize;

	if((oldSize = size) >= requiredSize)
		return;

	if((newSize = oldSize) == 0)
		newSize = initialSize;

	while(newSize < requiredSize)
		newSize *= 2;

	array = (HnSRTreeOffset **)xrealloc(array, sizeof(HnSRTreeOffset *) * newSize);

	size = newSize;
}

HnSRTreeOffsetArrayObj::HnSRTreeOffsetArrayObj(void)
{
	initialize();
}

HnSRTreeOffsetArrayObj::HnSRTreeOffsetArrayObj(const HnSRTreeOffsetArray &ptr)
{
	initialize();

	clear();
	append(ptr);
}

HnSRTreeOffsetArrayObj::~HnSRTreeOffsetArrayObj(void)
{
	dispose();
}

void
HnSRTreeOffsetArrayObj::clear(void)
{
	dispose();
}

void
HnSRTreeOffsetArrayObj::append(const HnSRTreeOffset &ptr)
{
	ensureSize(len + 1);

	array[len] = new HnSRTreeOffset(ptr);
	len ++;
}

void
HnSRTreeOffsetArrayObj::append(const HnSRTreeOffsetArray &ptr)
{
	int i;

	ensureSize(len + ptr.length());

	for(i=0; i<ptr.length(); i++)
		append(ptr[i]);
}

void
HnSRTreeOffsetArrayObj::insert(const HnSRTreeOffset &ptr, int index)
{
	if(index < 0 || index > len)
		HnAbort("HnSRTreeOffsetArrayObj::insert: "
			"index is out of bounds.");

	ensureSize(len + 1);

	memmove(array + index + 1, array + index,
		sizeof(HnSRTreeOffset *) * (len - index));

	array[index] = new HnSRTreeOffset(ptr);
	len ++;
}

HnSRTreeOffset
HnSRTreeOffsetArrayObj::remove(int index)
{
	HnSRTreeOffset ptr = get(index);

	if(index < 0 || index >= len)
                HnAbort("HnSRTreeOffsetArrayObj::remove: "
			"index is out of bounds.");

	delete array[index];

	memmove(array + index, array + index + 1,
		sizeof(HnSRTreeOffset *) * (len - index - 1));
	len --;

	return ptr;
}

void
HnSRTreeOffsetArrayObj::set(const HnSRTreeOffset &ptr, int index)
{
	if(index < 0 || index >= len)
		HnAbort("HnSRTreeOffsetArrayObj::set: "
			"index is out of bounds.");

	delete array[index];

	array[index] = new HnSRTreeOffset(ptr);
}

void
HnSRTreeOffsetArrayObj::swap(int i, int j)
{
	if(i < 0 || i >= len || j < 0 || j >= len)
		HnAbort("HnSRTreeOffsetArrayObj::swap: index is out of bounds.");

	HnSRTreeOffset *ptr = array[i];
	array[i] = array[j];
	array[j] = ptr;
}

HnSRTreeOffset &
HnSRTreeOffsetArrayObj::get(int i) const {
	if(i < 0 || i >= len)
		HnAbort("HnSRTreeOffsetArrayObj::get: index is out of bounds.");

	return *array[i];
}

HnBool
HnSRTreeOffsetArrayObj::equals(const HnSRTreeOffsetArray &ptr) const {
	int i;

	if(len != ptr.length())
		return HnFALSE;

	for(i=0; i<len; i++) {
		if(!array[i]->equals(ptr[i]))
			return HnFALSE;
	}

	return HnTRUE;
}

int
HnSRTreeOffsetArrayObj::indexOf(const HnSRTreeOffset &ptr, int fromIndex) const
{
	int i;

	for(i=fromIndex; i<len; i++) {
		if(array[i]->equals(ptr))
			return i;
	}

	return -1;
}

HnString
HnSRTreeOffsetArrayObj::toString(void) const
{
	HnString string;

	string = "[ ";
	for(int i=0; i<len; i++) {
		if(i != 0)
			string += ", ";
		string += array[i]->toString();
	}
	string += " ]";

	return string;
}

/*
 * HnSRTreeOffsetArray
 */

const HnSRTreeOffsetArray HnSRTreeOffsetArray::null;

HnSRTreeOffsetArray
new_HnSRTreeOffsetArray(void)
{
	HnSRTreeOffsetArray ptr;

        ptr.assign(new HnSRTreeOffsetArrayObj());
        return ptr;
}

HnSRTreeOffsetArray
new_HnSRTreeOffsetArray(const HnSRTreeOffsetArray &value)
{
	HnSRTreeOffsetArray ptr;

        if(value.isInvalid())
                ptr.assign(NULL);
        else
                ptr.assign(new HnSRTreeOffsetArrayObj(value));

        return ptr;
}

void
HnSRTreeOffsetArray::clear(void)
{
	getObject()->clear();
}

void
HnSRTreeOffsetArray::append(const HnSRTreeOffset &ptr)
{
	getObject()->append(ptr);
}

void
HnSRTreeOffsetArray::append(const HnSRTreeOffsetArray &ptr)
{
	getObject()->append(ptr);
}

void
HnSRTreeOffsetArray::insert(const HnSRTreeOffset &ptr, int index)
{
	getObject()->insert(ptr, index);
}

HnSRTreeOffset
HnSRTreeOffsetArray::remove(int index)
{
	return getObject()->remove(index);
}

void
HnSRTreeOffsetArray::set(const HnSRTreeOffset &ptr, int index)
{
	getObject()->set(ptr, index);
}

void
HnSRTreeOffsetArray::swap(int i, int j)
{
	getObject()->swap(i, j);
}

int
HnSRTreeOffsetArray::length(void) const
{
	return getObject()->length();
}

HnSRTreeOffset &
HnSRTreeOffsetArray::get(int i) const
{
	return getObject()->get(i);
}

HnBool
HnSRTreeOffsetArray::equals(const HnSRTreeOffsetArray &ptr) const
{
	return getObject()->equals(ptr);
}

int
HnSRTreeOffsetArray::indexOf(const HnSRTreeOffset &ptr, int fromIndex) const
{
	return getObject()->indexOf(ptr, fromIndex);
}

HnString
HnSRTreeOffsetArray::toString(void) const
{
	return getObject()->toString();
}

