/*
 * HnSRTreeBlock.cc
 *
 * DO NOT EDIT THIS FILE!
 *
 * This file is automatically generated by obj2ptr.
 * 1997/06/02 21:19:32
 */

#include "HnSRTreeBlock.hh"
#include "HnSRTreeBlockObj.hh"

/*
 * HnSRTreeBlock
 */

const HnSRTreeBlock HnSRTreeBlock::null;

HnSRTreeBlock
new_HnSRTreeBlock(off_t offset, const char *bytes, size_t size)
{
	HnSRTreeBlockObj *_obj;
	HnSRTreeBlock _ptr;

	_obj = new HnSRTreeBlockObj(offset, bytes, size);

	if(_obj->hasFailed())
		return HnSRTreeBlock::null;

	_ptr.assign(_obj);
	return _ptr;
}

off_t
HnSRTreeBlock::getOffset(void) const
{
	return getObject()->getOffset();
}

const char *
HnSRTreeBlock::getBytes(void) const
{
	return getObject()->getBytes();
}

size_t
HnSRTreeBlock::getSize(void) const
{
	return getObject()->getSize();
}

HnSRTreeBlock::Type
HnSRTreeBlock::getType(void) const
{
	return getObject()->getType();
}

HnBool
HnSRTreeBlock::isNode(void) const
{
	return getObject()->isNode();
}

HnBool
HnSRTreeBlock::isLeaf(void) const
{
	return getObject()->isLeaf();
}

HnBool
HnSRTreeBlock::isFree(void) const
{
	return getObject()->isFree();
}

/*
 * HnSRTreeBlockArrayObj
 */

#include <stdlib.h>
#include "HnString.hh"
class HnSRTreeBlockArrayObj: public HnObject {
private:
	HnSRTreeBlock **array;
	int len;
	int size;

	static const int initialSize;

	void initialize(void) {
		array = NULL;
		len = 0;
		size = 0;
	}
	void dispose(void) {
		if(array != NULL) {
			int i;
			for(i=0; i<len; i++)
				delete array[i];
			free(array);
		}
		array = NULL;
		len = 0;
		size = 0;
	}
	void ensureSize(int requiredSize);

public:
	/* constructor and destructor */
	HnSRTreeBlockArrayObj(void);
	HnSRTreeBlockArrayObj(const HnSRTreeBlockArray &ptr);
	~HnSRTreeBlockArrayObj(void);

	/* clear, append, insert, and remove */
	void clear(void);
	void append(const HnSRTreeBlock &ptr);
	void append(const HnSRTreeBlockArray &ptr);
	void insert(const HnSRTreeBlock &ptr, int index);
	HnSRTreeBlock remove(int index);
	void set(const HnSRTreeBlock &ptr, int index);
	void swap(int i, int j);

	/* length and get */
	int length(void) const { return len; }
	HnSRTreeBlock &get(int i) const;

	/* utilities */
	HnBool equals(const HnSRTreeBlockArray &ptr) const;
	int indexOf(const HnSRTreeBlock &ptr, int fromIndex) const;
	HnString toString(void) const;
};

const int HnSRTreeBlockArrayObj::initialSize = 4;

static void *
xrealloc(void *ptr, size_t size)
{
        if(ptr == NULL) {
                if((ptr = malloc(size)) == NULL)
                        HnSysError("malloc");
        }
        else {
                if((ptr = realloc(ptr, size)) == NULL)
                        HnSysError("realloc");
        }

        return ptr;
}

void
HnSRTreeBlockArrayObj::ensureSize(int requiredSize)
{
	int oldSize, newSize;

	if((oldSize = size) >= requiredSize)
		return;

	if((newSize = oldSize) == 0)
		newSize = initialSize;

	while(newSize < requiredSize)
		newSize *= 2;

	array = (HnSRTreeBlock **)xrealloc(array, sizeof(HnSRTreeBlock *) * newSize);

	size = newSize;
}

HnSRTreeBlockArrayObj::HnSRTreeBlockArrayObj(void)
{
	initialize();
}

HnSRTreeBlockArrayObj::HnSRTreeBlockArrayObj(const HnSRTreeBlockArray &ptr)
{
	initialize();

	clear();
	append(ptr);
}

HnSRTreeBlockArrayObj::~HnSRTreeBlockArrayObj(void)
{
	dispose();
}

void
HnSRTreeBlockArrayObj::clear(void)
{
	dispose();
}

void
HnSRTreeBlockArrayObj::append(const HnSRTreeBlock &ptr)
{
	ensureSize(len + 1);

	array[len] = new HnSRTreeBlock(ptr);
	len ++;
}

void
HnSRTreeBlockArrayObj::append(const HnSRTreeBlockArray &ptr)
{
	int i;

	ensureSize(len + ptr.length());

	for(i=0; i<ptr.length(); i++)
		append(ptr[i]);
}

void
HnSRTreeBlockArrayObj::insert(const HnSRTreeBlock &ptr, int index)
{
	if(index < 0 || index > len)
		HnAbort("HnSRTreeBlockArrayObj::insert: "
			"index is out of bounds.");

	ensureSize(len + 1);

	memmove(array + index + 1, array + index,
		sizeof(HnSRTreeBlock *) * (len - index));

	array[index] = new HnSRTreeBlock(ptr);
	len ++;
}

HnSRTreeBlock
HnSRTreeBlockArrayObj::remove(int index)
{
	HnSRTreeBlock ptr = get(index);

	if(index < 0 || index >= len)
                HnAbort("HnSRTreeBlockArrayObj::remove: "
			"index is out of bounds.");

	delete array[index];

	memmove(array + index, array + index + 1,
		sizeof(HnSRTreeBlock *) * (len - index - 1));
	len --;

	return ptr;
}

void
HnSRTreeBlockArrayObj::set(const HnSRTreeBlock &ptr, int index)
{
	if(index < 0 || index >= len)
		HnAbort("HnSRTreeBlockArrayObj::set: "
			"index is out of bounds.");

	delete array[index];

	array[index] = new HnSRTreeBlock(ptr);
}

void
HnSRTreeBlockArrayObj::swap(int i, int j)
{
	if(i < 0 || i >= len || j < 0 || j >= len)
		HnAbort("HnSRTreeBlockArrayObj::swap: index is out of bounds.");

	HnSRTreeBlock *ptr = array[i];
	array[i] = array[j];
	array[j] = ptr;
}

HnSRTreeBlock &
HnSRTreeBlockArrayObj::get(int i) const {
	if(i < 0 || i >= len)
		HnAbort("HnSRTreeBlockArrayObj::get: index is out of bounds.");

	return *array[i];
}

HnBool
HnSRTreeBlockArrayObj::equals(const HnSRTreeBlockArray &ptr) const {
	int i;

	if(len != ptr.length())
		return HnFALSE;

	for(i=0; i<len; i++) {
		if(!array[i]->equals(ptr[i]))
			return HnFALSE;
	}

	return HnTRUE;
}

int
HnSRTreeBlockArrayObj::indexOf(const HnSRTreeBlock &ptr, int fromIndex) const
{
	int i;

	for(i=fromIndex; i<len; i++) {
		if(array[i]->equals(ptr))
			return i;
	}

	return -1;
}

HnString
HnSRTreeBlockArrayObj::toString(void) const
{
	HnString string;

	string = "[ ";
	for(int i=0; i<len; i++) {
		if(i != 0)
			string += ", ";
		string += array[i]->toString();
	}
	string += " ]";

	return string;
}

/*
 * HnSRTreeBlockArray
 */

const HnSRTreeBlockArray HnSRTreeBlockArray::null;

HnSRTreeBlockArray
new_HnSRTreeBlockArray(void)
{
	HnSRTreeBlockArray ptr;

        ptr.assign(new HnSRTreeBlockArrayObj());
        return ptr;
}

HnSRTreeBlockArray
new_HnSRTreeBlockArray(const HnSRTreeBlockArray &value)
{
	HnSRTreeBlockArray ptr;

        if(value.isInvalid())
                ptr.assign(NULL);
        else
                ptr.assign(new HnSRTreeBlockArrayObj(value));

        return ptr;
}

void
HnSRTreeBlockArray::clear(void)
{
	getObject()->clear();
}

void
HnSRTreeBlockArray::append(const HnSRTreeBlock &ptr)
{
	getObject()->append(ptr);
}

void
HnSRTreeBlockArray::append(const HnSRTreeBlockArray &ptr)
{
	getObject()->append(ptr);
}

void
HnSRTreeBlockArray::insert(const HnSRTreeBlock &ptr, int index)
{
	getObject()->insert(ptr, index);
}

HnSRTreeBlock
HnSRTreeBlockArray::remove(int index)
{
	return getObject()->remove(index);
}

void
HnSRTreeBlockArray::set(const HnSRTreeBlock &ptr, int index)
{
	getObject()->set(ptr, index);
}

void
HnSRTreeBlockArray::swap(int i, int j)
{
	getObject()->swap(i, j);
}

int
HnSRTreeBlockArray::length(void) const
{
	return getObject()->length();
}

HnSRTreeBlock &
HnSRTreeBlockArray::get(int i) const
{
	return getObject()->get(i);
}

HnBool
HnSRTreeBlockArray::equals(const HnSRTreeBlockArray &ptr) const
{
	return getObject()->equals(ptr);
}

int
HnSRTreeBlockArray::indexOf(const HnSRTreeBlock &ptr, int fromIndex) const
{
	return getObject()->indexOf(ptr, fromIndex);
}

HnString
HnSRTreeBlockArray::toString(void) const
{
	return getObject()->toString();
}

