/*
 * HnSRTreeNeighbor.cc
 *
 * DO NOT EDIT THIS FILE!
 *
 * This file is automatically generated by obj2ptr.
 * 1997/06/02 21:19:34
 */

#include "HnSRTreeNeighbor.hh"
#include "HnSRTreeNeighborObj.hh"

/*
 * HnSRTreeNeighbor
 */

const HnSRTreeNeighbor HnSRTreeNeighbor::null;

HnSRTreeNeighbor
new_HnSRTreeNeighbor(const HnPoint &point, const HnData &data, double distance)
{
	HnSRTreeNeighborObj *_obj;
	HnSRTreeNeighbor _ptr;

	_obj = new HnSRTreeNeighborObj(point, data, distance);

	if(_obj->hasFailed())
		return HnSRTreeNeighbor::null;

	_ptr.assign(_obj);
	return _ptr;
}

HnPoint
HnSRTreeNeighbor::getPoint(void) const
{
	return getObject()->getPoint();
}

HnData
HnSRTreeNeighbor::getData(void) const
{
	return getObject()->getData();
}

double
HnSRTreeNeighbor::getDistance(void) const
{
	return getObject()->getDistance();
}

HnString
HnSRTreeNeighbor::toString(void) const {
	if(isInvalid())
		return "HnSRTreeNeighbor::null";
    	else
		return getObject()->toString();
}

HnSRTreeNeighborArray
HnSRTreeNeighbor::sort(const HnSRTreeNeighborArray &ptr)
{
	return HnSRTreeNeighborObj::sort(ptr);
}

/*
 * HnSRTreeNeighborArrayObj
 */

#include <stdlib.h>
#include "HnString.hh"
class HnSRTreeNeighborArrayObj: public HnObject {
private:
	HnSRTreeNeighbor **array;
	int len;
	int size;

	static const int initialSize;

	void initialize(void) {
		array = NULL;
		len = 0;
		size = 0;
	}
	void dispose(void) {
		if(array != NULL) {
			int i;
			for(i=0; i<len; i++)
				delete array[i];
			free(array);
		}
		array = NULL;
		len = 0;
		size = 0;
	}
	void ensureSize(int requiredSize);

public:
	/* constructor and destructor */
	HnSRTreeNeighborArrayObj(void);
	HnSRTreeNeighborArrayObj(const HnSRTreeNeighborArray &ptr);
	~HnSRTreeNeighborArrayObj(void);

	/* clear, append, insert, and remove */
	void clear(void);
	void append(const HnSRTreeNeighbor &ptr);
	void append(const HnSRTreeNeighborArray &ptr);
	void insert(const HnSRTreeNeighbor &ptr, int index);
	HnSRTreeNeighbor remove(int index);
	void set(const HnSRTreeNeighbor &ptr, int index);
	void swap(int i, int j);

	/* length and get */
	int length(void) const { return len; }
	HnSRTreeNeighbor &get(int i) const;

	/* utilities */
	HnBool equals(const HnSRTreeNeighborArray &ptr) const;
	int indexOf(const HnSRTreeNeighbor &ptr, int fromIndex) const;
	HnString toString(void) const;
};

const int HnSRTreeNeighborArrayObj::initialSize = 4;

static void *
xrealloc(void *ptr, size_t size)
{
        if(ptr == NULL) {
                if((ptr = malloc(size)) == NULL)
                        HnSysError("malloc");
        }
        else {
                if((ptr = realloc(ptr, size)) == NULL)
                        HnSysError("realloc");
        }

        return ptr;
}

void
HnSRTreeNeighborArrayObj::ensureSize(int requiredSize)
{
	int oldSize, newSize;

	if((oldSize = size) >= requiredSize)
		return;

	if((newSize = oldSize) == 0)
		newSize = initialSize;

	while(newSize < requiredSize)
		newSize *= 2;

	array = (HnSRTreeNeighbor **)xrealloc(array, sizeof(HnSRTreeNeighbor *) * newSize);

	size = newSize;
}

HnSRTreeNeighborArrayObj::HnSRTreeNeighborArrayObj(void)
{
	initialize();
}

HnSRTreeNeighborArrayObj::HnSRTreeNeighborArrayObj(const HnSRTreeNeighborArray &ptr)
{
	initialize();

	clear();
	append(ptr);
}

HnSRTreeNeighborArrayObj::~HnSRTreeNeighborArrayObj(void)
{
	dispose();
}

void
HnSRTreeNeighborArrayObj::clear(void)
{
	dispose();
}

void
HnSRTreeNeighborArrayObj::append(const HnSRTreeNeighbor &ptr)
{
	ensureSize(len + 1);

	array[len] = new HnSRTreeNeighbor(ptr);
	len ++;
}

void
HnSRTreeNeighborArrayObj::append(const HnSRTreeNeighborArray &ptr)
{
	int i;

	ensureSize(len + ptr.length());

	for(i=0; i<ptr.length(); i++)
		append(ptr[i]);
}

void
HnSRTreeNeighborArrayObj::insert(const HnSRTreeNeighbor &ptr, int index)
{
	if(index < 0 || index > len)
		HnAbort("HnSRTreeNeighborArrayObj::insert: "
			"index is out of bounds.");

	ensureSize(len + 1);

	memmove(array + index + 1, array + index,
		sizeof(HnSRTreeNeighbor *) * (len - index));

	array[index] = new HnSRTreeNeighbor(ptr);
	len ++;
}

HnSRTreeNeighbor
HnSRTreeNeighborArrayObj::remove(int index)
{
	HnSRTreeNeighbor ptr = get(index);

	if(index < 0 || index >= len)
                HnAbort("HnSRTreeNeighborArrayObj::remove: "
			"index is out of bounds.");

	delete array[index];

	memmove(array + index, array + index + 1,
		sizeof(HnSRTreeNeighbor *) * (len - index - 1));
	len --;

	return ptr;
}

void
HnSRTreeNeighborArrayObj::set(const HnSRTreeNeighbor &ptr, int index)
{
	if(index < 0 || index >= len)
		HnAbort("HnSRTreeNeighborArrayObj::set: "
			"index is out of bounds.");

	delete array[index];

	array[index] = new HnSRTreeNeighbor(ptr);
}

void
HnSRTreeNeighborArrayObj::swap(int i, int j)
{
	if(i < 0 || i >= len || j < 0 || j >= len)
		HnAbort("HnSRTreeNeighborArrayObj::swap: index is out of bounds.");

	HnSRTreeNeighbor *ptr = array[i];
	array[i] = array[j];
	array[j] = ptr;
}

HnSRTreeNeighbor &
HnSRTreeNeighborArrayObj::get(int i) const {
	if(i < 0 || i >= len)
		HnAbort("HnSRTreeNeighborArrayObj::get: index is out of bounds.");

	return *array[i];
}

HnBool
HnSRTreeNeighborArrayObj::equals(const HnSRTreeNeighborArray &ptr) const {
	int i;

	if(len != ptr.length())
		return HnFALSE;

	for(i=0; i<len; i++) {
		if(!array[i]->equals(ptr[i]))
			return HnFALSE;
	}

	return HnTRUE;
}

int
HnSRTreeNeighborArrayObj::indexOf(const HnSRTreeNeighbor &ptr, int fromIndex) const
{
	int i;

	for(i=fromIndex; i<len; i++) {
		if(array[i]->equals(ptr))
			return i;
	}

	return -1;
}

HnString
HnSRTreeNeighborArrayObj::toString(void) const
{
	HnString string;

	string = "[ ";
	for(int i=0; i<len; i++) {
		if(i != 0)
			string += ", ";
		string += array[i]->toString();
	}
	string += " ]";

	return string;
}

/*
 * HnSRTreeNeighborArray
 */

const HnSRTreeNeighborArray HnSRTreeNeighborArray::null;

HnSRTreeNeighborArray
new_HnSRTreeNeighborArray(void)
{
	HnSRTreeNeighborArray ptr;

        ptr.assign(new HnSRTreeNeighborArrayObj());
        return ptr;
}

HnSRTreeNeighborArray
new_HnSRTreeNeighborArray(const HnSRTreeNeighborArray &value)
{
	HnSRTreeNeighborArray ptr;

        if(value.isInvalid())
                ptr.assign(NULL);
        else
                ptr.assign(new HnSRTreeNeighborArrayObj(value));

        return ptr;
}

void
HnSRTreeNeighborArray::clear(void)
{
	getObject()->clear();
}

void
HnSRTreeNeighborArray::append(const HnSRTreeNeighbor &ptr)
{
	getObject()->append(ptr);
}

void
HnSRTreeNeighborArray::append(const HnSRTreeNeighborArray &ptr)
{
	getObject()->append(ptr);
}

void
HnSRTreeNeighborArray::insert(const HnSRTreeNeighbor &ptr, int index)
{
	getObject()->insert(ptr, index);
}

HnSRTreeNeighbor
HnSRTreeNeighborArray::remove(int index)
{
	return getObject()->remove(index);
}

void
HnSRTreeNeighborArray::set(const HnSRTreeNeighbor &ptr, int index)
{
	getObject()->set(ptr, index);
}

void
HnSRTreeNeighborArray::swap(int i, int j)
{
	getObject()->swap(i, j);
}

int
HnSRTreeNeighborArray::length(void) const
{
	return getObject()->length();
}

HnSRTreeNeighbor &
HnSRTreeNeighborArray::get(int i) const
{
	return getObject()->get(i);
}

HnBool
HnSRTreeNeighborArray::equals(const HnSRTreeNeighborArray &ptr) const
{
	return getObject()->equals(ptr);
}

int
HnSRTreeNeighborArray::indexOf(const HnSRTreeNeighbor &ptr, int fromIndex) const
{
	return getObject()->indexOf(ptr, fromIndex);
}

HnString
HnSRTreeNeighborArray::toString(void) const
{
	return getObject()->toString();
}

